apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swrta-fran
  name: swrta-fran
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: swrta-fran
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: swrta-fran
    spec:
      containers:
        - env:
            - name: TF_SERVING_URL
              valueFrom:
                configMapKeyRef:
                  key: TF_SERVING_URL
                  name: swrta-fran-config-vixj
            - name: SWARMFARM_URL
              valueFrom:
                configMapKeyRef:
                  key: SWARMFARM_URL
                  name: swrta-fran-config-vixj
          image: gcr.io/swrta-278814/github_jessinra_swrta-fran
          imagePullPolicy: IfNotPresent
          name: swrta-fran-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: swrta-fran
  namespace: default
spec:
  maxReplicas: 2
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: swrta-fran
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: swrta-fran
  name: swrta-fran-service
  namespace: default
spec:
  clusterIP: 10.36.2.176
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32099
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: swrta-fran
  sessionAffinity: None
  type: NodePort
